#!/usr/bin/perl -wT
use strict;
use warnings;

# Untaint
$ENV{'PATH'} = '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin';
delete @ENV{'IFS', 'CDPATH', 'ENV', 'BASH_ENV'};

use CBitcoin;
use CBitcoin::CLI::SPV;


CBitcoin::CLI::SPV::run_cli_args(@ARGV);

exit 0;

__END__






