#!/usr/bin/env perl -wT
use strict;
use warnings;



# Untaint
$ENV{'PATH'} = '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin';
delete @ENV{'IFS', 'CDPATH', 'ENV', 'BASH_ENV'};

CBitcoin::CLI::SPV::run_cli_args(@ARGV);

exit 0;

__END__






